### ISSUE TITLE
Does kliff only support periodic systems?

### ISSUE THREAD

**Issue by chemxyang** [mjwen/kliff#2]
Dear Mingjian,

I found the "Lattice" is required in the extxyz file, otherwise, the code would throw an error. Does that mean current version of kliff only support periodic systems?
If it is the truth, do you plan to add the support of non-periodic system in the further>

Best wishes,

Xin

**Comment by mjwen** [comment]
Hi Xin,

KLIFF do support non-periodic systems. In "Lattice", you need to provide the three lattice vectors of the simulation box, so it has nothing to do with periodic boundary conditions (PBCs). Instead, you can specify PBCs along the three lattice vectors using the "PBC" key in the extended XYZ file. For example, PBC="1 0 0" means use PBC along the first lattice vector direction but not the second and third directions. See [the docs](https://kliff.readthedocs.io/en/latest/modules/dataset.html#extended-xyz) for more.
