### ISSUE TITLE
How to use trained KIM model?

### ISSUE THREAD

**Issue by ruoitrau86** [mjwen/kliff#5]
Hi,
After training we can save the trained model to a KIM model:
`model.write_kim_model()`
By default it will save as NeuralNetwork_KLIFF__MO_000000111111_000 which will use DUNN_WT__MD_000000111111_000 as its driver. I wonder how to install this driver to use the trained KIM model. An example script will be very appreciated.

**Comment by mjwen** [comment]
I was out of town on a vacation and sorry for the late response... 

You can find the related info on [Install a KLIFF-trained model](https://kliff.readthedocs.io/en/stable/howto/install_kim_model.html#install-a-kliff-trained-model) at the KLIFF doc page. Specifically for the NN model, the [driver](https://openkim.org/id/DUNN__MD_292677547454_000) name is changed to `DUNN__MD_292677547454_000` when it was uploaded to the KIM repository.

You can install this driver by: 
``` bash
kim-api-collections-management install user DUNN__MD_292677547454_000
```

Then install the trained model by:

``` bash
kim-api-collections-management install user NeuralNetwork_KLIFF__MO_000000111111_000
```

Note, you need to change line 18 of `CMakeLists.txt` to use the updated driver name. (If you pull the latest code from the repo, this is handled automatically and you do not need to manually make any change).
