### ISSUE TITLE
What unit does a trained potential use?

### ISSUE THREAD

**Issue by funan-jhc-lee** [mjwen/kliff#7]
Hello,
     I'm trying to train a NN potential for lammps, and I wonder what unit does the trained potential use? Is it the same with the trainset? And If I want to change the unit  the potential use, I need to change the unit of trainset?
Thanks a lot!

**Comment by mjwen** [comment]
Yes, you are right. KLIFF doesn't have the notion of units. It fits to the data you specified in the training set and you need to change the units directly in the training set.

**Comment by funan-jhc-lee** [comment]
> Yes, you are right. KLIFF doesn't have the notion of units. It fits to the data you specified in the training set and you need to change the units directly in the training set.

**Comment by funan-jhc-lee** [comment]
> Yes, you are right. KLIFF doesn't have the notion of units. It fits to the data you specified in the training set and you need to change the units directly in the training set.

Thanks a lot for your reply!
